-- Seed all Polish vocabulary (pl_001 through pl_210) into vocab and vocab_translation tables.
-- The theme_vocab mappings for pl_theme10/11 are seeded in 012 (which
-- inserts the theme rows first so the FKs are satisfied).

-- Widen vocab.gender to allow 'n' (neutral). The 001 baseline only
-- allows 'm'/'f', but pl_211+ in 013 use 'n' for neuter nouns.
ALTER TABLE vocab DROP CONSTRAINT IF EXISTS vocab_gender_check;
ALTER TABLE vocab ADD CONSTRAINT vocab_gender_check
  CHECK (gender IS NULL OR gender IN ('m', 'f', 'n'));

-- 1. Insert vocab entries
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_001', 'tak', '/tak/', NULL, 1, 'basics') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_002', 'nie', '/ɲɛ/', NULL, 2, 'basics') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_003', 'cześć', '/ˈtʂɛɕtɕ/', NULL, 3, 'greetings') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_004', 'dzień dobry', '/ˈdʑɛɲ ˈdɔbrɨ/', NULL, 4, 'greetings') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_005', 'dobry wieczór', '/ˈdɔbrɨ ˈvʲɛtʂur/', NULL, 5, 'greetings') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_006', 'dobranoc', '/dɔˈbranɔts/', NULL, 6, 'greetings') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_007', 'do widzenia', '/dɔ vʲidˈzɛɲa/', NULL, 7, 'greetings') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_008', 'proszę', '/ˈprɔʃɛ/', NULL, 8, 'basics') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_009', 'dziękuję', '/dʑɛŋˈkujɛ/', NULL, 9, 'basics') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_010', 'przepraszam', '/pʃɛpraˈʃam/', NULL, 10, 'basics') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_011', 'ja', '/ja/', NULL, 11, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_012', 'ty', '/tɨ/', NULL, 12, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_013', 'on', '/ɔn/', NULL, 13, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_014', 'ona', '/ˈɔna/', NULL, 14, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_015', 'my', '/mɨ/', NULL, 15, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_016', 'wy', '/vɨ/', NULL, 16, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_017', 'oni', '/ˈɔɲi/', NULL, 17, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_018', 'one', '/ˈɔnɛ/', NULL, 18, 'pronouns') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_019', 'być', '/bɨtʂ/', NULL, 20, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_020', 'jestem', '/ˈjɛstɛm/', NULL, 21, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_021', 'jesteś', '/ˈjɛstɛɕ/', NULL, 22, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_022', 'jest', '/jɛst/', NULL, 23, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_023', 'jesteśmy', '/ˈjɛstɛzmɨ/', NULL, 24, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_024', 'jesteście', '/ˈjɛstɛɕtɕɛ/', NULL, 25, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_025', 'są', '/sɔ̃/', NULL, 26, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_026', 'człowiek', '/ˈtʂwɔvʲɛk/', 'm', 30, 'people') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_027', 'mężczyzna', '/mɛŋʃˈtʂɨzna/', 'm', 31, 'people') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_028', 'kobieta', '/kɔˈbʲɛta/', 'f', 32, 'people') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_029', 'dziecko', '/ˈdʑɛtʂkɔ/', 'n', 33, 'people') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_030', 'chłopiec', '/ˈxwɔpʲɛts/', 'm', 34, 'people') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_031', 'dziewczyna', '/dʑɛfˈtʂɨna/', 'f', 35, 'people') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_032', 'rodzina', '/rɔˈdʑina/', 'f', 40, 'family') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_033', 'matka', '/ˈmatka/', 'f', 41, 'family') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_034', 'ojciec', '/ˈɔjtʂɛts/', 'm', 42, 'family') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_035', 'siostra', '/ˈɕɔstra/', 'f', 43, 'family') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_036', 'brat', '/brat/', 'm', 44, 'family') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_037', 'jeden', '/ˈjɛdɛn/', NULL, 50, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_038', 'dwa', '/dva/', NULL, 51, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_039', 'trzy', '/tʃɨ/', NULL, 52, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_040', 'cztery', '/ˈtʂtɛrɨ/', NULL, 53, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_041', 'pięć', '/pʲɛɲtʂ/', NULL, 54, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_042', 'sześć', '/ˈʃɛɕtʂ/', NULL, 55, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_043', 'siedem', '/ˈɕɛdɛm/', NULL, 56, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_044', 'osiem', '/ˈɔɕɛm/', NULL, 57, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_045', 'dziewięć', '/dʑɛˈvʲɛɲtʂ/', NULL, 58, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_046', 'dziesięć', '/dʑɛˈɕɛɲtʂ/', NULL, 59, 'numbers') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_047', 'teraz', '/ˈtɛras/', NULL, 60, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_048', 'dziś', '/dʑiɕ/', NULL, 61, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_049', 'jutro', '/ˈjutrɔ/', NULL, 62, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_050', 'wczoraj', '/ˈftʃɔraj/', NULL, 63, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_051', 'rano', '/ˈrano/', NULL, 64, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_052', 'wieczór', '/ˈvʲɛtʂur/', NULL, 65, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_053', 'noc', '/nɔts/', NULL, 66, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_054', 'dzień', '/dʑɛɲ/', NULL, 67, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_055', 'tydzień', '/ˈtɨdʑɛɲ/', NULL, 68, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_056', 'miesiąc', '/ˈmʲɛɕɔnts/', NULL, 69, 'time') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_057', 'dom', '/dɔm/', 'm', 70, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_058', 'mieszkanie', '/mʲɛˈʃkaɲɛ/', 'n', 71, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_059', 'miasto', '/ˈmʲastɔ/', 'n', 72, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_060', 'wioska', '/ˈvʲɔska/', 'f', 73, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_061', 'ulica', '/ˈulitsa/', 'f', 74, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_062', 'sklep', '/sklɛp/', 'm', 75, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_063', 'restauracja', '/rɛstauˈratsja/', 'f', 76, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_064', 'szkoła', '/ˈʃkɔwa/', 'f', 77, 'places') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_065', 'praca', '/ˈpratsa/', 'f', 78, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_066', 'mieć', '/mʲɛtʂ/', NULL, 80, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_067', 'robić', '/ˈrɔbʲitʂ/', NULL, 81, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_068', 'iść', '/iɕtʂ/', NULL, 82, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_069', 'jechać', '/ˈjɛxatʂ/', NULL, 83, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_070', 'mówić', '/ˈmuvʲitʂ/', NULL, 84, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_071', 'rozumieć', '/rɔˈzʊmʲɛtʂ/', NULL, 85, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_072', 'jeść', '/jɛɕtʂ/', NULL, 86, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_073', 'pić', '/pʲitʂ/', NULL, 87, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_074', 'spać', '/spaɲtʂ/', NULL, 88, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_075', 'uczyć się', '/ˈutʂɨtʂ ɕɛ/', NULL, 89, 'verbs') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_076', 'woda', '/ˈvoda/', 'f', 90, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_077', 'chleb', '/xlɛp/', 'm', 91, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_078', 'masło', '/ˈmaswɔ/', 'n', 92, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_079', 'mięso', '/ˈmʲɛɲsɔ/', 'n', 93, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_080', 'kurczak', '/ˈkurtʃak/', 'm', 94, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_081', 'ryba', '/ˈrɨba/', 'f', 95, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_082', 'ser', '/sɛr/', 'm', 96, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_083', 'mleko', '/ˈmlɛkɔ/', 'n', 97, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_084', 'jajko', '/ˈjajkɔ/', 'n', 98, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_085', 'owoc', '/ˈɔvɔts/', 'm', 99, 'food') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_086', 'duży', '/ˈduʒɨ/', NULL, 100, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_087', 'mały', '/ˈmawɨ/', NULL, 101, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_088', 'dobry', '/ˈdɔbrɨ/', NULL, 102, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_089', 'zły', '/zwɨ/', NULL, 103, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_090', 'nowy', '/ˈnɔvɨ/', NULL, 104, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_091', 'stary', '/ˈstarɨ/', NULL, 105, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_092', 'ładny', '/ˈwadnɨ/', NULL, 106, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_093', 'brzydki', '/ˈbʒɨtkʲi/', NULL, 107, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_094', 'szybki', '/ˈʃɨpkʲi/', NULL, 108, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_095', 'wolny', '/ˈvɔlnɨ/', NULL, 109, 'adjectives') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_096', 'zawód', '/ˈzavut/', 'm', 110, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_097', 'specjalista', '/spɛt͡sjaˈlista/', 'm', 111, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_098', 'kariera', '/kaˈrjɛra/', 'f', 112, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_099', 'ścieżka kariery', '/ˈɕtɛʂka kaˈrjɛrɨ/', 'f', 113, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_100', 'rynek pracy', '/ˈrɨnɛk ˈprat͡sɨ/', 'm', 114, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_101', 'pracodawca', '/prat͡sɔˈdaft͡sa/', 'm', 115, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_102', 'pracownik', '/praˈt͡sɔvɲik/', 'm', 116, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_103', 'kolega', '/kɔˈlɛɡa/', 'm', 117, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_104', 'zespół', '/ˈzɛspuw/', 'm', 118, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_105', 'szef', '/ʂɛf/', 'm', 119, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_106', 'przełożony', '/pʂɛwɔˈʐɔnɨ/', 'm', 120, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_107', 'kierownictwo', '/kʲɛrɔvˈɲit͡stvɔ/', 'n', 121, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_108', 'rozmowa kwalifikacyjna', '/rɔzˈmɔva kwalifiˈkat͡sɨjna/', 'f', 122, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_109', 'CV', '/t͡sɛ vu/', 'n', 123, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_110', 'poszukiwanie pracy', '/pɔʂukiˈvaɲɛ ˈprat͡sɨ/', 'n', 124, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_111', 'znaleźć pracę', '/ˈznalɛɕt͡ɕ ˈprat͡sɛ/', NULL, 125, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_112', 'stracić pracę', '/ˈstrat͡ɕit͡ɕ ˈprat͡sɛ/', NULL, 126, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_113', 'zmienić pracę', '/ˈzmʲɛɲit͡ɕ ˈprat͡sɛ/', NULL, 127, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_114', 'awans', '/ˈavans/', 'm', 128, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_115', 'podwyżka', '/pɔdˈvɨʂka/', 'f', 129, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_116', 'pensja', '/ˈpɛɲsja/', 'f', 130, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_117', 'wynagrodzenie', '/vɨnaɡrɔˈd͡zɛɲɛ/', 'n', 131, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_118', 'premia', '/ˈprɛmja/', 'f', 132, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_119', 'bonus', '/ˈbɔnus/', 'm', 133, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_120', 'dzień roboczy', '/dʑɛɲ rɔˈbɔt͡ʂɨ/', 'm', 134, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_121', 'godziny pracy', '/ɡɔˈd͡zɨnɨ ˈprat͡sɨ/', 'f', 135, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_122', 'nadgodziny', '/naɡɡɔˈd͡zɨnɨ/', 'f', 136, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_123', 'weekend', '/viˈkɛnd/', 'm', 137, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_124', 'urlop', '/ˈurlɔp/', 'm', 138, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_125', 'zwolnienie lekarskie', '/zvɔlˈɲɛɲɛ lɛˈkarskʲɛ/', 'n', 139, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_126', 'praca zdalna', '/ˈprat͡sa ˈzdalna/', 'f', 140, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_127', 'praca w biurze', '/ˈprat͡sa v ˈbʲurʑɛ/', 'f', 141, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_128', 'praca hybrydowa', '/ˈprat͡sa xɨˈbrɨdɔva/', 'f', 142, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_129', 'freelancing', '/ˈfrɛlansʲiŋk/', 'm', 143, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_130', 'samozatrudniony', '/samɔzatruˈdɲɔnɨ/', 'm', 144, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_131', 'przedsiębiorca', '/pʂɛd͡ɕɛmˈbjɔrt͡sa/', 'm', 145, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_132', 'własna firma', '/ˈvwasna ˈfirma/', 'f', 146, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_133', 'biznes', '/ˈbʲiznɛs/', 'm', 147, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_134', 'obowiązki', '/ɔbɔˈvjɔɲt͡ski/', 'm', 148, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_135', 'projekt', '/ˈprɔjɛkt/', 'm', 149, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_136', 'zadanie', '/zaˈdaɲɛ/', 'n', 150, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_137', 'termin', '/ˈtɛrmin/', 'm', 151, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_138', 'satysfakcja z pracy', '/satɨsˈfakt͡sja z ˈprat͡sɨ/', 'f', 152, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_139', 'bezrobocie', '/bɛzrɔˈbɔt͡sɛ/', 'n', 153, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_140', 'bezrobotny', '/bɛzrɔˈbɔtnɨ/', 'm', 154, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_141', 'automatyzacja', '/awtɔmatɨˈzat͡sja/', 'f', 155, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_142', 'sztuczna inteligencja', '/ˈʂtut͡ʂna intɛliˈɡɛnt͡sja/', 'f', 156, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_143', 'przekwalifikowanie', '/pʂɛkvalifiˈkɔvaɲɛ/', 'n', 157, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_144', 'staż', '/staʂ/', 'm', 158, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_145', 'równowaga między pracą a życiem', '/ruvˈnɔvaɡa ˈmʲɛndzɨ ˈprat͡sɔ̃ a ˈʐɨt͡ɕɛm/', 'f', 159, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_146', 'stres w pracy', '/strɛs v ˈprat͡sɨ/', 'm', 160, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_147', 'wypalenie zawodowe', '/vɨpaˈlɛɲɛ zavɔˈdɔvɛ/', 'n', 161, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_148', 'profesjonalizm', '/prɔfɛsjɔˈnalizm/', 'm', 162, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_149', 'produktywność', '/prɔduktɨvˈnɔɕt͡ɕ/', 'f', 163, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_150', 'uczciwość', '/ut͡ʂˈt͡ɕivɔɕt͡ɕ/', 'f', 164, 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_151', 'wykształcenie', '/vɨkʂtawˈt͡sɛɲɛ/', 'n', 165, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_152', 'system edukacji', '/ˈsɨstɛm ɛduˈkat͡sji/', 'm', 166, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_153', 'nauczyciel', '/nauˈt͡ʂɨt͡ɕɛl/', 'm', 167, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_154', 'nauczycielka', '/nauˈt͡ʂɨt͡ɕɛlka/', 'f', 168, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_155', 'uczeń', '/ˈut͡ʂɛɲ/', 'm', 169, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_156', 'uczennica', '/ut͡ʂɛɲˈɲit͡sa/', 'f', 170, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_157', 'lekcja', '/ˈlɛkt͡sja/', 'f', 171, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_158', 'zajęcia', '/zaˈjɛɲt͡ɕa/', 'n', 172, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_159', 'zajęcia dodatkowe', '/zaˈjɛɲt͡ɕa dɔdatˈkɔvɛ/', 'n', 173, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_160', 'przedmiot', '/ˈpʂɛdmʲɔt/', 'm', 174, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_161', 'ulubiony przedmiot', '/uluˈbjɔnɨ ˈpʂɛdmʲɔt/', 'm', 175, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_162', 'ocena', '/ˈɔt͡sɛna/', 'f', 176, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_163', 'praca domowa', '/ˈprat͡sa dɔˈmɔva/', 'f', 177, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_164', 'egzamin', '/ɛɡˈzamʲin/', 'm', 178, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_165', 'egzamin ustny', '/ɛɡˈzamʲin ˈustnɨ/', 'm', 179, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_166', 'zdający', '/ˈzdajɔnt͡sɨ/', 'm', 180, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_167', 'egzaminator', '/ɛɡzamʲiˈnatɔr/', 'm', 181, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_168', 'zdać egzamin', '/ˈzdat͡ɕ ɛɡˈzamʲin/', NULL, 182, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_169', 'podręcznik', '/pɔdrɛt͡ʂˈɲik/', 'm', 183, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_170', 'zeszyt', '/ˈzɛʂɨt/', 'm', 184, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_171', 'tablica', '/taˈblit͡sa/', 'f', 185, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_172', 'ławka', '/ˈwafka/', 'f', 186, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_173', 'program nauczania', '/ˈprɔɡram nauˈt͡ʂaɲa/', 'm', 187, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_174', 'metody nauczania', '/ˈmɛtɔdɨ nauˈt͡ʂaɲa/', 'f', 188, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_175', 'nauka zdalna', '/ˈnauka ˈzdalna/', 'f', 189, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_176', 'nauka stacjonarna', '/ˈnauka stat͡sjɔˈnarna/', 'f', 190, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_177', 'model hybrydowy', '/ˈmɔdɛl xɨˈbrɨdɔvɨ/', 'm', 191, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_178', 'zajęcia online', '/zaˈjɛɲt͡ɕa ˈɔnlajn/', 'n', 192, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_179', 'platforma', '/platˈfɔrma/', 'f', 193, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_180', 'wideokonferencja', '/vʲidɛɔkɔnfɛˈrɛnt͡sja/', 'f', 194, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_181', 'szkoła językowa', '/ˈʃkɔwa jɛŋˈzɨkɔva/', 'f', 195, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_182', 'absolwent', '/abˈsɔlvɛnt/', 'm', 196, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_183', 'absolwentka', '/absɔlˈvɛntka/', 'f', 197, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_184', 'dyplom', '/ˈdɨplɔm/', 'm', 198, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_185', 'certyfikat', '/t͡sɛrtɨˈfikat/', 'm', 199, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_186', 'uniwersytet', '/uɲivɛrˈsɨtɛt/', 'm', 200, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_187', 'uczelnia', '/uˈt͡ʂɛlɲa/', 'f', 201, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_188', 'wyższe wykształcenie', '/ˈvɨʂʂɛ vɨkʂtawˈt͡sɛɲɛ/', 'n', 202, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_189', 'wydział', '/ˈvɨd͡ʑaw/', 'm', 203, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_190', 'studia', '/ˈstudja/', 'n', 204, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_191', 'darmowa edukacja', '/darˈmɔva ɛduˈkat͡sja/', 'f', 205, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_192', 'płatna edukacja', '/ˈpwatna ɛduˈkat͡sja/', 'f', 206, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_193', 'zdolny', '/ˈzdɔlnɨ/', NULL, 207, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_194', 'talent', '/ˈtalɛnt/', 'm', 208, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_195', 'utalentowany', '/utalɛnˈtɔvanɨ/', 'm', 209, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_196', 'umiejętność', '/umʲɛˈjɛntɔɕt͡ɕ/', 'f', 210, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_197', 'wiedza', '/ˈvʲɛdza/', 'f', 211, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_198', 'krytyczne myślenie', '/krɨˈtɨt͡ʂnɛ mɨɕˈlɛɲɛ/', 'n', 212, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_199', 'komunikacja', '/kɔmuɲiˈkat͡sja/', 'f', 213, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_200', 'praca zespołowa', '/ˈprat͡sa zɛspɔˈwɔva/', 'f', 214, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_201', 'fiszki', '/ˈfʲiʂci/', 'f', 215, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_202', 'powtórki interwałowe', '/pɔfˈturki intɛrvaˈwɔvɛ/', 'f', 216, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_203', 'uczyć się samodzielnie', '/ˈut͡ʂɨt͡ɕ ɕɛ samɔˈd͡ʑɛlɲɛ/', NULL, 217, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_204', 'uczyć się w grupie', '/ˈut͡ʂɨt͡ɕ ɕɛ v ˈɡrupʲɛ/', NULL, 218, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_205', 'klasa', '/ˈklasa/', 'f', 219, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_206', 'laptop', '/ˈlaptɔp/', 'm', 220, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_207', 'komputer', '/kɔmˈputɛr/', 'm', 221, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_208', 'słuchawki', '/swuˈxafci/', 'f', 222, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_209', 'wykładowca', '/vɨkwaˈdɔft͡sa/', 'm', 223, 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab (id, target, ipa, gender, freq, theme) VALUES ('pl_210', 'rówieśnicy', '/ruvʲɛɕˈɲit͡sɨ/', 'm', 224, 'education') ON CONFLICT DO NOTHING;

-- 2. Insert translations (ru + en)
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_001', 'ru', 'да') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_001', 'en', 'yes') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_002', 'ru', 'нет') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_002', 'en', 'no') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_003', 'ru', 'привет') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_003', 'en', 'hi') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_004', 'ru', 'добрый день') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_004', 'en', 'good day') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_005', 'ru', 'добрый вечер') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_005', 'en', 'good evening') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_006', 'ru', 'спокойной ночи') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_006', 'en', 'good night') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_007', 'ru', 'до свидания') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_007', 'en', 'goodbye') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_008', 'ru', 'пожалуйста') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_008', 'en', 'please') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_009', 'ru', 'спасибо') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_009', 'en', 'thank you') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_010', 'ru', 'извините') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_010', 'en', 'sorry') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_011', 'ru', 'я') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_011', 'en', 'I') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_012', 'ru', 'ты') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_012', 'en', 'you (singular)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_013', 'ru', 'он') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_013', 'en', 'he') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_014', 'ru', 'она') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_014', 'en', 'she') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_015', 'ru', 'мы') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_015', 'en', 'we') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_016', 'ru', 'вы') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_016', 'en', 'you (plural)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_017', 'ru', 'они (м.р.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_017', 'en', 'they (masc.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_018', 'ru', 'они (жен.р.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_018', 'en', 'they (fem.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_019', 'ru', 'быть') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_019', 'en', 'to be') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_020', 'ru', 'я есть (буду)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_020', 'en', 'I am') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_021', 'ru', 'ты есть (будешь)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_021', 'en', 'you are') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_022', 'ru', 'он/она есть (будет)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_022', 'en', 'he/she is') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_023', 'ru', 'мы есть (будем)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_023', 'en', 'we are') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_024', 'ru', 'вы есть (будете)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_024', 'en', 'you (pl.) are') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_025', 'ru', 'они есть (будут)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_025', 'en', 'they are') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_026', 'ru', 'человек') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_026', 'en', 'person') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_027', 'ru', 'мужчина') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_027', 'en', 'man') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_028', 'ru', 'женщина') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_028', 'en', 'woman') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_029', 'ru', 'ребёнок') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_029', 'en', 'child') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_030', 'ru', 'мальчик') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_030', 'en', 'boy') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_031', 'ru', 'девочка') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_031', 'en', 'girl') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_032', 'ru', 'семья') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_032', 'en', 'family') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_033', 'ru', 'мать') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_033', 'en', 'mother') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_034', 'ru', 'отец') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_034', 'en', 'father') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_035', 'ru', 'сестра') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_035', 'en', 'sister') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_036', 'ru', 'брат') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_036', 'en', 'brother') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_037', 'ru', 'один') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_037', 'en', 'one') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_038', 'ru', 'два') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_038', 'en', 'two') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_039', 'ru', 'три') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_039', 'en', 'three') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_040', 'ru', 'четыре') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_040', 'en', 'four') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_041', 'ru', 'пять') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_041', 'en', 'five') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_042', 'ru', 'шесть') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_042', 'en', 'six') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_043', 'ru', 'семь') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_043', 'en', 'seven') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_044', 'ru', 'восемь') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_044', 'en', 'eight') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_045', 'ru', 'девять') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_045', 'en', 'nine') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_046', 'ru', 'десять') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_046', 'en', 'ten') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_047', 'ru', 'сейчас') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_047', 'en', 'now') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_048', 'ru', 'сегодня') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_048', 'en', 'today') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_049', 'ru', 'завтра') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_049', 'en', 'tomorrow') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_050', 'ru', 'вчера') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_050', 'en', 'yesterday') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_051', 'ru', 'утро') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_051', 'en', 'morning') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_052', 'ru', 'вечер') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_052', 'en', 'evening') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_053', 'ru', 'ночь') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_053', 'en', 'night') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_054', 'ru', 'день') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_054', 'en', 'day') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_055', 'ru', 'неделя') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_055', 'en', 'week') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_056', 'ru', 'месяц') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_056', 'en', 'month') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_057', 'ru', 'дом') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_057', 'en', 'house') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_058', 'ru', 'квартира') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_058', 'en', 'apartment') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_059', 'ru', 'город') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_059', 'en', 'city') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_060', 'ru', 'деревня') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_060', 'en', 'village') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_061', 'ru', 'улица') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_061', 'en', 'street') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_062', 'ru', 'магазин') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_062', 'en', 'shop') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_063', 'ru', 'ресторан') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_063', 'en', 'restaurant') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_064', 'ru', 'школа') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_064', 'en', 'school') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_065', 'ru', 'работа') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_065', 'en', 'work') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_066', 'ru', 'иметь') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_066', 'en', 'to have') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_067', 'ru', 'делать') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_067', 'en', 'to do/make') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_068', 'ru', 'идти') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_068', 'en', 'to go') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_069', 'ru', 'ехать') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_069', 'en', 'to travel') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_070', 'ru', 'говорить') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_070', 'en', 'to speak') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_071', 'ru', 'понимать') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_071', 'en', 'to understand') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_072', 'ru', 'есть') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_072', 'en', 'to eat') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_073', 'ru', 'пить') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_073', 'en', 'to drink') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_074', 'ru', 'спать') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_074', 'en', 'to sleep') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_075', 'ru', 'учиться') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_075', 'en', 'to learn') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_076', 'ru', 'вода') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_076', 'en', 'water') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_077', 'ru', 'хлеб') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_077', 'en', 'bread') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_078', 'ru', 'масло') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_078', 'en', 'butter') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_079', 'ru', 'мясо') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_079', 'en', 'meat') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_080', 'ru', 'курица') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_080', 'en', 'chicken') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_081', 'ru', 'рыба') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_081', 'en', 'fish') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_082', 'ru', 'сыр') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_082', 'en', 'cheese') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_083', 'ru', 'молоко') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_083', 'en', 'milk') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_084', 'ru', 'яйцо') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_084', 'en', 'egg') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_085', 'ru', 'фрукт') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_085', 'en', 'fruit') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_086', 'ru', 'большой') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_086', 'en', 'big') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_087', 'ru', 'маленький') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_087', 'en', 'small') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_088', 'ru', 'хороший') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_088', 'en', 'good') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_089', 'ru', 'плохой') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_089', 'en', 'bad') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_090', 'ru', 'новый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_090', 'en', 'new') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_091', 'ru', 'старый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_091', 'en', 'old') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_092', 'ru', 'красивый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_092', 'en', 'beautiful') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_093', 'ru', 'уродливый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_093', 'en', 'ugly') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_094', 'ru', 'быстрый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_094', 'en', 'fast') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_095', 'ru', 'медленный') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_095', 'en', 'slow') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_096', 'ru', 'профессия') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_096', 'en', 'profession') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_097', 'ru', 'специалист') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_097', 'en', 'specialist') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_098', 'ru', 'карьера') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_098', 'en', 'career') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_099', 'ru', 'карьерный путь') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_099', 'en', 'career path') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_100', 'ru', 'рынок труда') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_100', 'en', 'job market') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_101', 'ru', 'работодатель') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_101', 'en', 'employer') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_102', 'ru', 'работник') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_102', 'en', 'employee') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_103', 'ru', 'коллега') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_103', 'en', 'colleague') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_104', 'ru', 'команда') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_104', 'en', 'team') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_105', 'ru', 'босс') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_105', 'en', 'boss') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_106', 'ru', 'начальник') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_106', 'en', 'supervisor') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_107', 'ru', 'руководство') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_107', 'en', 'management') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_108', 'ru', 'собеседование') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_108', 'en', 'job interview') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_109', 'ru', 'резюме') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_109', 'en', 'CV / resume') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_110', 'ru', 'поиск работы') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_110', 'en', 'job search') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_111', 'ru', 'найти работу') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_111', 'en', 'to find a job') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_112', 'ru', 'потерять работу') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_112', 'en', 'to lose a job') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_113', 'ru', 'сменить работу') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_113', 'en', 'to change jobs') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_114', 'ru', 'повышение') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_114', 'en', 'promotion') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_115', 'ru', 'повышение зарплаты') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_115', 'en', 'pay raise') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_116', 'ru', 'зарплата') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_116', 'en', 'salary') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_117', 'ru', 'вознаграждение') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_117', 'en', 'compensation') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_118', 'ru', 'премия') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_118', 'en', 'bonus') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_119', 'ru', 'бонус') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_119', 'en', 'bonus') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_120', 'ru', 'рабочий день') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_120', 'en', 'workday') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_121', 'ru', 'рабочее время') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_121', 'en', 'working hours') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_122', 'ru', 'сверхурочные') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_122', 'en', 'overtime') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_123', 'ru', 'выходные') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_123', 'en', 'weekend') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_124', 'ru', 'отпуск') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_124', 'en', 'vacation') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_125', 'ru', 'больничный') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_125', 'en', 'sick leave') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_126', 'ru', 'удалённая работа') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_126', 'en', 'remote work') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_127', 'ru', 'работа в офисе') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_127', 'en', 'office work') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_128', 'ru', 'гибридная работа') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_128', 'en', 'hybrid work') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_129', 'ru', 'фриланс') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_129', 'en', 'freelancing') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_130', 'ru', 'самозанятый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_130', 'en', 'self-employed') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_131', 'ru', 'предприниматель') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_131', 'en', 'entrepreneur') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_132', 'ru', 'своя фирма') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_132', 'en', 'own company') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_133', 'ru', 'бизнес') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_133', 'en', 'business') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_134', 'ru', 'обязанности') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_134', 'en', 'responsibilities') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_135', 'ru', 'проект') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_135', 'en', 'project') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_136', 'ru', 'задача') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_136', 'en', 'task') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_137', 'ru', 'дедлайн / срок') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_137', 'en', 'deadline') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_138', 'ru', 'удовлетворение от работы') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_138', 'en', 'job satisfaction') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_139', 'ru', 'безработица') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_139', 'en', 'unemployment') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_140', 'ru', 'безработный') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_140', 'en', 'unemployed') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_141', 'ru', 'автоматизация') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_141', 'en', 'automation') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_142', 'ru', 'искусственный интеллект') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_142', 'en', 'artificial intelligence') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_143', 'ru', 'переквалификация') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_143', 'en', 'retraining') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_144', 'ru', 'стажировка') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_144', 'en', 'internship') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_145', 'ru', 'баланс работы и жизни') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_145', 'en', 'work-life balance') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_146', 'ru', 'стресс на работе') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_146', 'en', 'work stress') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_147', 'ru', 'профессиональное выгорание') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_147', 'en', 'burnout') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_148', 'ru', 'профессионализм') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_148', 'en', 'professionalism') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_149', 'ru', 'продуктивность') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_149', 'en', 'productivity') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_150', 'ru', 'честность') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_150', 'en', 'honesty') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_151', 'ru', 'образование') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_151', 'en', 'education') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_152', 'ru', 'система образования') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_152', 'en', 'education system') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_153', 'ru', 'учитель') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_153', 'en', 'teacher') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_154', 'ru', 'учительница') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_154', 'en', 'teacher (fem.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_155', 'ru', 'ученик') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_155', 'en', 'student (pupil)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_156', 'ru', 'ученица') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_156', 'en', 'student (fem.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_157', 'ru', 'урок') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_157', 'en', 'lesson') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_158', 'ru', 'занятия') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_158', 'en', 'classes') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_159', 'ru', 'дополнительные занятия') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_159', 'en', 'extracurricular classes') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_160', 'ru', 'предмет') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_160', 'en', 'subject') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_161', 'ru', 'любимый предмет') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_161', 'en', 'favourite subject') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_162', 'ru', 'оценка') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_162', 'en', 'grade') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_163', 'ru', 'домашнее задание') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_163', 'en', 'homework') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_164', 'ru', 'экзамен') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_164', 'en', 'exam') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_165', 'ru', 'устный экзамен') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_165', 'en', 'oral exam') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_166', 'ru', 'сдающий экзамен') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_166', 'en', 'exam candidate') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_167', 'ru', 'экзаменатор') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_167', 'en', 'examiner') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_168', 'ru', 'сдать экзамен') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_168', 'en', 'to pass an exam') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_169', 'ru', 'учебник') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_169', 'en', 'textbook') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_170', 'ru', 'тетрадь') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_170', 'en', 'notebook') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_171', 'ru', 'доска') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_171', 'en', 'board') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_172', 'ru', 'парта') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_172', 'en', 'desk') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_173', 'ru', 'программа обучения') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_173', 'en', 'curriculum') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_174', 'ru', 'методы обучения') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_174', 'en', 'teaching methods') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_175', 'ru', 'дистанционное обучение') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_175', 'en', 'distance learning') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_176', 'ru', 'очное обучение') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_176', 'en', 'in-person learning') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_177', 'ru', 'гибридная модель') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_177', 'en', 'hybrid model') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_178', 'ru', 'онлайн-занятия') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_178', 'en', 'online classes') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_179', 'ru', 'платформа') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_179', 'en', 'platform') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_180', 'ru', 'видеоконференция') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_180', 'en', 'video conference') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_181', 'ru', 'языковая школа') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_181', 'en', 'language school') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_182', 'ru', 'выпускник') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_182', 'en', 'graduate') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_183', 'ru', 'выпускница') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_183', 'en', 'graduate (fem.)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_184', 'ru', 'диплом') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_184', 'en', 'diploma') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_185', 'ru', 'сертификат') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_185', 'en', 'certificate') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_186', 'ru', 'университет') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_186', 'en', 'university') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_187', 'ru', 'вуз') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_187', 'en', 'college') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_188', 'ru', 'высшее образование') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_188', 'en', 'higher education') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_189', 'ru', 'факультет') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_189', 'en', 'faculty') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_190', 'ru', 'учебные курсы / учёба в вузе') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_190', 'en', 'university studies') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_191', 'ru', 'бесплатное образование') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_191', 'en', 'free education') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_192', 'ru', 'платное образование') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_192', 'en', 'paid education') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_193', 'ru', 'способный') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_193', 'en', 'talented / capable') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_194', 'ru', 'талант') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_194', 'en', 'talent') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_195', 'ru', 'талантливый') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_195', 'en', 'talented') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_196', 'ru', 'навык / умение') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_196', 'en', 'skill') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_197', 'ru', 'знание') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_197', 'en', 'knowledge') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_198', 'ru', 'критическое мышление') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_198', 'en', 'critical thinking') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_199', 'ru', 'коммуникация') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_199', 'en', 'communication') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_200', 'ru', 'работа в команде') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_200', 'en', 'teamwork') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_201', 'ru', 'карточки для запоминания') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_201', 'en', 'flashcards') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_202', 'ru', 'интервальное повторение') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_202', 'en', 'spaced repetition') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_203', 'ru', 'учиться самостоятельно') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_203', 'en', 'to study independently') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_204', 'ru', 'учиться в группе') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_204', 'en', 'to study in a group') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_205', 'ru', 'класс') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_205', 'en', 'class') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_206', 'ru', 'ноутбук') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_206', 'en', 'laptop') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_207', 'ru', 'компьютер') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_207', 'en', 'computer') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_208', 'ru', 'наушники') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_208', 'en', 'headphones') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_209', 'ru', 'преподаватель (вуз)') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_209', 'en', 'lecturer') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_210', 'ru', 'сверстники') ON CONFLICT DO NOTHING;
INSERT INTO vocab_translation (vocab_id, lang, text) VALUES ('pl_210', 'en', 'peers') ON CONFLICT DO NOTHING;

-- 5. Mark migration as applied
INSERT INTO _migrations (name) VALUES ('011_seed_polish_vocab.sql') ON CONFLICT DO NOTHING;
